# Generated by Django 3.2.7 on 2021-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealname', models.CharField(max_length=100)),
                ('mealdescription', models.CharField(max_length=255)),
                ('mealtype', models.CharField(max_length=50)),
                ('mealprice', models.FloatField()),
            ],
        ),
    ]
