# Generated by Django 3.2.7 on 2021-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkname', models.CharField(max_length=100)),
                ('drinkdescription', models.CharField(max_length=255)),
                ('drinktype', models.CharField(max_length=50)),
                ('drinkprice', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='meals',
            new_name='meal',
        ),
    ]
