# Generated by Django 3.2.7 on 2021-10-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211001_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='drinkprice',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='mealprice',
        ),
    ]
