# Generated by Django 3.2.7 on 2021-10-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211001_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drinkprice',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='mealprice',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
    ]
